version: '3'

tasks:
  default:
    cmds:
      - echo "Hello World"

  test:
    cmds:
      - python3 -m unittest discover -k "test_*.py"


  rm-pdfs:
    cmds:
      - cd fig && rm *.pdf

  rm-pngs:
    cmds:
      - cd fig && rm *.png

  textlint:  
    cmds:
      - npx textlint {{ .CLI_ARGS }}

  pdfsync:
    cmds:
      - curl -X POST -F file=$(base64 out/main.pdf) $GAS_API_URL

  init:
    cmds:
      - |
       touch .env
       npm install
       brew install --cask drawio